<?php

use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_form_alter().
 *
 * Remove top messenger errors for THIS specific form only.
 */
function my_form_demo_form_alter(array &$form, FormStateInterface $form_state, $form_id) {
// print_r($form_id);exit;
  // Match your form ID
  if ($form_id === 'example_form') {

    // Disable top messages block
    $form['#disable_inline_form_errors'] = TRUE;

    // Force remove any existing messages
  }
}
